// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datanode.proto

#include "datanode.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace bdfs {
class keepalive_reqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<keepalive_req>
      _instance;
} _keepalive_req_default_instance_;
class keepalive_respDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<keepalive_resp>
      _instance;
} _keepalive_resp_default_instance_;
class connect_reqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<connect_req>
      _instance;
} _connect_req_default_instance_;
class connect_respDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<connect_resp>
      _instance;
} _connect_resp_default_instance_;
class disconnect_reqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<disconnect_req>
      _instance;
} _disconnect_req_default_instance_;
class disconnect_respDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<disconnect_resp>
      _instance;
} _disconnect_resp_default_instance_;
}  // namespace bdfs
namespace protobuf_datanode_2eproto {
void InitDefaultskeepalive_reqImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::bdfs::_keepalive_req_default_instance_;
    new (ptr) ::bdfs::keepalive_req();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bdfs::keepalive_req::InitAsDefaultInstance();
}

void InitDefaultskeepalive_req() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultskeepalive_reqImpl);
}

void InitDefaultskeepalive_respImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::bdfs::_keepalive_resp_default_instance_;
    new (ptr) ::bdfs::keepalive_resp();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bdfs::keepalive_resp::InitAsDefaultInstance();
}

void InitDefaultskeepalive_resp() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultskeepalive_respImpl);
}

void InitDefaultsconnect_reqImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::bdfs::_connect_req_default_instance_;
    new (ptr) ::bdfs::connect_req();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bdfs::connect_req::InitAsDefaultInstance();
}

void InitDefaultsconnect_req() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsconnect_reqImpl);
}

void InitDefaultsconnect_respImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::bdfs::_connect_resp_default_instance_;
    new (ptr) ::bdfs::connect_resp();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bdfs::connect_resp::InitAsDefaultInstance();
}

void InitDefaultsconnect_resp() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsconnect_respImpl);
}

void InitDefaultsdisconnect_reqImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::bdfs::_disconnect_req_default_instance_;
    new (ptr) ::bdfs::disconnect_req();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bdfs::disconnect_req::InitAsDefaultInstance();
}

void InitDefaultsdisconnect_req() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsdisconnect_reqImpl);
}

void InitDefaultsdisconnect_respImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::bdfs::_disconnect_resp_default_instance_;
    new (ptr) ::bdfs::disconnect_resp();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bdfs::disconnect_resp::InitAsDefaultInstance();
}

void InitDefaultsdisconnect_resp() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsdisconnect_respImpl);
}

::google::protobuf::Metadata file_level_metadata[6];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bdfs::keepalive_req, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bdfs::keepalive_req, nodename_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bdfs::keepalive_resp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bdfs::keepalive_resp, nodename_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bdfs::connect_req, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bdfs::connect_req, ipaddress_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bdfs::connect_req, nodename_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bdfs::connect_req, sizegb_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bdfs::connect_resp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bdfs::connect_resp, ipaddress_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bdfs::connect_resp, nodename_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bdfs::connect_resp, sizegb_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bdfs::disconnect_req, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bdfs::disconnect_req, ipaddress_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bdfs::disconnect_req, nodename_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bdfs::disconnect_resp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bdfs::disconnect_resp, ipaddress_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bdfs::disconnect_resp, nodename_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::bdfs::keepalive_req)},
  { 6, -1, sizeof(::bdfs::keepalive_resp)},
  { 12, -1, sizeof(::bdfs::connect_req)},
  { 20, -1, sizeof(::bdfs::connect_resp)},
  { 28, -1, sizeof(::bdfs::disconnect_req)},
  { 35, -1, sizeof(::bdfs::disconnect_resp)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::bdfs::_keepalive_req_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::bdfs::_keepalive_resp_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::bdfs::_connect_req_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::bdfs::_connect_resp_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::bdfs::_disconnect_req_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::bdfs::_disconnect_resp_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "datanode.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 6);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\016datanode.proto\022\004bdfs\"!\n\rkeepalive_req\022"
      "\020\n\010nodename\030\001 \001(\t\"\"\n\016keepalive_resp\022\020\n\010n"
      "odename\030\001 \001(\t\"B\n\013connect_req\022\021\n\tipaddres"
      "s\030\001 \001(\t\022\020\n\010nodename\030\002 \001(\t\022\016\n\006sizeGB\030\003 \001("
      "\003\"C\n\014connect_resp\022\021\n\tipaddress\030\001 \001(\t\022\020\n\010"
      "nodename\030\002 \001(\t\022\016\n\006sizeGB\030\003 \001(\003\"5\n\016discon"
      "nect_req\022\021\n\tipaddress\030\001 \001(\t\022\020\n\010nodename\030"
      "\002 \001(\t\"6\n\017disconnect_resp\022\021\n\tipaddress\030\001 "
      "\001(\t\022\020\n\010nodename\030\002 \001(\t2\312\001\n\010FSServer\022\?\n\020pr"
      "ocessKeepalive\022\023.bdfs.keepalive_req\032\024.bd"
      "fs.keepalive_resp\"\000\0229\n\016processConnect\022\021."
      "bdfs.connect_req\032\022.bdfs.connect_resp\"\000\022B"
      "\n\021processDisconnect\022\024.bdfs.disconnect_re"
      "q\032\025.bdfs.disconnect_resp\"\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 554);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "datanode.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_datanode_2eproto
namespace bdfs {

// ===================================================================

void keepalive_req::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int keepalive_req::kNodenameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

keepalive_req::keepalive_req()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_datanode_2eproto::InitDefaultskeepalive_req();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:bdfs.keepalive_req)
}
keepalive_req::keepalive_req(const keepalive_req& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  nodename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.nodename().size() > 0) {
    nodename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nodename_);
  }
  // @@protoc_insertion_point(copy_constructor:bdfs.keepalive_req)
}

void keepalive_req::SharedCtor() {
  nodename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

keepalive_req::~keepalive_req() {
  // @@protoc_insertion_point(destructor:bdfs.keepalive_req)
  SharedDtor();
}

void keepalive_req::SharedDtor() {
  nodename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void keepalive_req::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* keepalive_req::descriptor() {
  ::protobuf_datanode_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_datanode_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const keepalive_req& keepalive_req::default_instance() {
  ::protobuf_datanode_2eproto::InitDefaultskeepalive_req();
  return *internal_default_instance();
}

keepalive_req* keepalive_req::New(::google::protobuf::Arena* arena) const {
  keepalive_req* n = new keepalive_req;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void keepalive_req::Clear() {
// @@protoc_insertion_point(message_clear_start:bdfs.keepalive_req)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  nodename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool keepalive_req::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:bdfs.keepalive_req)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string nodename = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_nodename()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->nodename().data(), static_cast<int>(this->nodename().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "bdfs.keepalive_req.nodename"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:bdfs.keepalive_req)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:bdfs.keepalive_req)
  return false;
#undef DO_
}

void keepalive_req::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:bdfs.keepalive_req)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string nodename = 1;
  if (this->nodename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nodename().data(), static_cast<int>(this->nodename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.keepalive_req.nodename");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->nodename(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:bdfs.keepalive_req)
}

::google::protobuf::uint8* keepalive_req::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:bdfs.keepalive_req)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string nodename = 1;
  if (this->nodename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nodename().data(), static_cast<int>(this->nodename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.keepalive_req.nodename");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->nodename(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bdfs.keepalive_req)
  return target;
}

size_t keepalive_req::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bdfs.keepalive_req)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string nodename = 1;
  if (this->nodename().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->nodename());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void keepalive_req::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bdfs.keepalive_req)
  GOOGLE_DCHECK_NE(&from, this);
  const keepalive_req* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const keepalive_req>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bdfs.keepalive_req)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bdfs.keepalive_req)
    MergeFrom(*source);
  }
}

void keepalive_req::MergeFrom(const keepalive_req& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bdfs.keepalive_req)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.nodename().size() > 0) {

    nodename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nodename_);
  }
}

void keepalive_req::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bdfs.keepalive_req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void keepalive_req::CopyFrom(const keepalive_req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bdfs.keepalive_req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool keepalive_req::IsInitialized() const {
  return true;
}

void keepalive_req::Swap(keepalive_req* other) {
  if (other == this) return;
  InternalSwap(other);
}
void keepalive_req::InternalSwap(keepalive_req* other) {
  using std::swap;
  nodename_.Swap(&other->nodename_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata keepalive_req::GetMetadata() const {
  protobuf_datanode_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_datanode_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void keepalive_resp::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int keepalive_resp::kNodenameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

keepalive_resp::keepalive_resp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_datanode_2eproto::InitDefaultskeepalive_resp();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:bdfs.keepalive_resp)
}
keepalive_resp::keepalive_resp(const keepalive_resp& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  nodename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.nodename().size() > 0) {
    nodename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nodename_);
  }
  // @@protoc_insertion_point(copy_constructor:bdfs.keepalive_resp)
}

void keepalive_resp::SharedCtor() {
  nodename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

keepalive_resp::~keepalive_resp() {
  // @@protoc_insertion_point(destructor:bdfs.keepalive_resp)
  SharedDtor();
}

void keepalive_resp::SharedDtor() {
  nodename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void keepalive_resp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* keepalive_resp::descriptor() {
  ::protobuf_datanode_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_datanode_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const keepalive_resp& keepalive_resp::default_instance() {
  ::protobuf_datanode_2eproto::InitDefaultskeepalive_resp();
  return *internal_default_instance();
}

keepalive_resp* keepalive_resp::New(::google::protobuf::Arena* arena) const {
  keepalive_resp* n = new keepalive_resp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void keepalive_resp::Clear() {
// @@protoc_insertion_point(message_clear_start:bdfs.keepalive_resp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  nodename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool keepalive_resp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:bdfs.keepalive_resp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string nodename = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_nodename()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->nodename().data(), static_cast<int>(this->nodename().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "bdfs.keepalive_resp.nodename"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:bdfs.keepalive_resp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:bdfs.keepalive_resp)
  return false;
#undef DO_
}

void keepalive_resp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:bdfs.keepalive_resp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string nodename = 1;
  if (this->nodename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nodename().data(), static_cast<int>(this->nodename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.keepalive_resp.nodename");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->nodename(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:bdfs.keepalive_resp)
}

::google::protobuf::uint8* keepalive_resp::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:bdfs.keepalive_resp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string nodename = 1;
  if (this->nodename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nodename().data(), static_cast<int>(this->nodename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.keepalive_resp.nodename");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->nodename(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bdfs.keepalive_resp)
  return target;
}

size_t keepalive_resp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bdfs.keepalive_resp)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string nodename = 1;
  if (this->nodename().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->nodename());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void keepalive_resp::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bdfs.keepalive_resp)
  GOOGLE_DCHECK_NE(&from, this);
  const keepalive_resp* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const keepalive_resp>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bdfs.keepalive_resp)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bdfs.keepalive_resp)
    MergeFrom(*source);
  }
}

void keepalive_resp::MergeFrom(const keepalive_resp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bdfs.keepalive_resp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.nodename().size() > 0) {

    nodename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nodename_);
  }
}

void keepalive_resp::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bdfs.keepalive_resp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void keepalive_resp::CopyFrom(const keepalive_resp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bdfs.keepalive_resp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool keepalive_resp::IsInitialized() const {
  return true;
}

void keepalive_resp::Swap(keepalive_resp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void keepalive_resp::InternalSwap(keepalive_resp* other) {
  using std::swap;
  nodename_.Swap(&other->nodename_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata keepalive_resp::GetMetadata() const {
  protobuf_datanode_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_datanode_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void connect_req::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int connect_req::kIpaddressFieldNumber;
const int connect_req::kNodenameFieldNumber;
const int connect_req::kSizeGBFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

connect_req::connect_req()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_datanode_2eproto::InitDefaultsconnect_req();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:bdfs.connect_req)
}
connect_req::connect_req(const connect_req& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ipaddress_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.ipaddress().size() > 0) {
    ipaddress_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ipaddress_);
  }
  nodename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.nodename().size() > 0) {
    nodename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nodename_);
  }
  sizegb_ = from.sizegb_;
  // @@protoc_insertion_point(copy_constructor:bdfs.connect_req)
}

void connect_req::SharedCtor() {
  ipaddress_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nodename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sizegb_ = GOOGLE_LONGLONG(0);
  _cached_size_ = 0;
}

connect_req::~connect_req() {
  // @@protoc_insertion_point(destructor:bdfs.connect_req)
  SharedDtor();
}

void connect_req::SharedDtor() {
  ipaddress_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nodename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void connect_req::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* connect_req::descriptor() {
  ::protobuf_datanode_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_datanode_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const connect_req& connect_req::default_instance() {
  ::protobuf_datanode_2eproto::InitDefaultsconnect_req();
  return *internal_default_instance();
}

connect_req* connect_req::New(::google::protobuf::Arena* arena) const {
  connect_req* n = new connect_req;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void connect_req::Clear() {
// @@protoc_insertion_point(message_clear_start:bdfs.connect_req)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ipaddress_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nodename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sizegb_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool connect_req::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:bdfs.connect_req)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string ipaddress = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ipaddress()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->ipaddress().data(), static_cast<int>(this->ipaddress().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "bdfs.connect_req.ipaddress"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string nodename = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_nodename()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->nodename().data(), static_cast<int>(this->nodename().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "bdfs.connect_req.nodename"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 sizeGB = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &sizegb_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:bdfs.connect_req)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:bdfs.connect_req)
  return false;
#undef DO_
}

void connect_req::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:bdfs.connect_req)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ipaddress = 1;
  if (this->ipaddress().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ipaddress().data(), static_cast<int>(this->ipaddress().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.connect_req.ipaddress");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->ipaddress(), output);
  }

  // string nodename = 2;
  if (this->nodename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nodename().data(), static_cast<int>(this->nodename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.connect_req.nodename");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->nodename(), output);
  }

  // int64 sizeGB = 3;
  if (this->sizegb() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->sizegb(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:bdfs.connect_req)
}

::google::protobuf::uint8* connect_req::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:bdfs.connect_req)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ipaddress = 1;
  if (this->ipaddress().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ipaddress().data(), static_cast<int>(this->ipaddress().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.connect_req.ipaddress");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->ipaddress(), target);
  }

  // string nodename = 2;
  if (this->nodename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nodename().data(), static_cast<int>(this->nodename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.connect_req.nodename");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->nodename(), target);
  }

  // int64 sizeGB = 3;
  if (this->sizegb() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->sizegb(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bdfs.connect_req)
  return target;
}

size_t connect_req::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bdfs.connect_req)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string ipaddress = 1;
  if (this->ipaddress().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->ipaddress());
  }

  // string nodename = 2;
  if (this->nodename().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->nodename());
  }

  // int64 sizeGB = 3;
  if (this->sizegb() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->sizegb());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void connect_req::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bdfs.connect_req)
  GOOGLE_DCHECK_NE(&from, this);
  const connect_req* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const connect_req>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bdfs.connect_req)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bdfs.connect_req)
    MergeFrom(*source);
  }
}

void connect_req::MergeFrom(const connect_req& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bdfs.connect_req)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ipaddress().size() > 0) {

    ipaddress_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ipaddress_);
  }
  if (from.nodename().size() > 0) {

    nodename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nodename_);
  }
  if (from.sizegb() != 0) {
    set_sizegb(from.sizegb());
  }
}

void connect_req::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bdfs.connect_req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void connect_req::CopyFrom(const connect_req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bdfs.connect_req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool connect_req::IsInitialized() const {
  return true;
}

void connect_req::Swap(connect_req* other) {
  if (other == this) return;
  InternalSwap(other);
}
void connect_req::InternalSwap(connect_req* other) {
  using std::swap;
  ipaddress_.Swap(&other->ipaddress_);
  nodename_.Swap(&other->nodename_);
  swap(sizegb_, other->sizegb_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata connect_req::GetMetadata() const {
  protobuf_datanode_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_datanode_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void connect_resp::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int connect_resp::kIpaddressFieldNumber;
const int connect_resp::kNodenameFieldNumber;
const int connect_resp::kSizeGBFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

connect_resp::connect_resp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_datanode_2eproto::InitDefaultsconnect_resp();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:bdfs.connect_resp)
}
connect_resp::connect_resp(const connect_resp& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ipaddress_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.ipaddress().size() > 0) {
    ipaddress_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ipaddress_);
  }
  nodename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.nodename().size() > 0) {
    nodename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nodename_);
  }
  sizegb_ = from.sizegb_;
  // @@protoc_insertion_point(copy_constructor:bdfs.connect_resp)
}

void connect_resp::SharedCtor() {
  ipaddress_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nodename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sizegb_ = GOOGLE_LONGLONG(0);
  _cached_size_ = 0;
}

connect_resp::~connect_resp() {
  // @@protoc_insertion_point(destructor:bdfs.connect_resp)
  SharedDtor();
}

void connect_resp::SharedDtor() {
  ipaddress_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nodename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void connect_resp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* connect_resp::descriptor() {
  ::protobuf_datanode_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_datanode_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const connect_resp& connect_resp::default_instance() {
  ::protobuf_datanode_2eproto::InitDefaultsconnect_resp();
  return *internal_default_instance();
}

connect_resp* connect_resp::New(::google::protobuf::Arena* arena) const {
  connect_resp* n = new connect_resp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void connect_resp::Clear() {
// @@protoc_insertion_point(message_clear_start:bdfs.connect_resp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ipaddress_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nodename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sizegb_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool connect_resp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:bdfs.connect_resp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string ipaddress = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ipaddress()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->ipaddress().data(), static_cast<int>(this->ipaddress().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "bdfs.connect_resp.ipaddress"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string nodename = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_nodename()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->nodename().data(), static_cast<int>(this->nodename().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "bdfs.connect_resp.nodename"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 sizeGB = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &sizegb_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:bdfs.connect_resp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:bdfs.connect_resp)
  return false;
#undef DO_
}

void connect_resp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:bdfs.connect_resp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ipaddress = 1;
  if (this->ipaddress().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ipaddress().data(), static_cast<int>(this->ipaddress().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.connect_resp.ipaddress");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->ipaddress(), output);
  }

  // string nodename = 2;
  if (this->nodename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nodename().data(), static_cast<int>(this->nodename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.connect_resp.nodename");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->nodename(), output);
  }

  // int64 sizeGB = 3;
  if (this->sizegb() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->sizegb(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:bdfs.connect_resp)
}

::google::protobuf::uint8* connect_resp::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:bdfs.connect_resp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ipaddress = 1;
  if (this->ipaddress().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ipaddress().data(), static_cast<int>(this->ipaddress().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.connect_resp.ipaddress");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->ipaddress(), target);
  }

  // string nodename = 2;
  if (this->nodename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nodename().data(), static_cast<int>(this->nodename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.connect_resp.nodename");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->nodename(), target);
  }

  // int64 sizeGB = 3;
  if (this->sizegb() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->sizegb(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bdfs.connect_resp)
  return target;
}

size_t connect_resp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bdfs.connect_resp)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string ipaddress = 1;
  if (this->ipaddress().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->ipaddress());
  }

  // string nodename = 2;
  if (this->nodename().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->nodename());
  }

  // int64 sizeGB = 3;
  if (this->sizegb() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->sizegb());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void connect_resp::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bdfs.connect_resp)
  GOOGLE_DCHECK_NE(&from, this);
  const connect_resp* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const connect_resp>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bdfs.connect_resp)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bdfs.connect_resp)
    MergeFrom(*source);
  }
}

void connect_resp::MergeFrom(const connect_resp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bdfs.connect_resp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ipaddress().size() > 0) {

    ipaddress_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ipaddress_);
  }
  if (from.nodename().size() > 0) {

    nodename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nodename_);
  }
  if (from.sizegb() != 0) {
    set_sizegb(from.sizegb());
  }
}

void connect_resp::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bdfs.connect_resp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void connect_resp::CopyFrom(const connect_resp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bdfs.connect_resp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool connect_resp::IsInitialized() const {
  return true;
}

void connect_resp::Swap(connect_resp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void connect_resp::InternalSwap(connect_resp* other) {
  using std::swap;
  ipaddress_.Swap(&other->ipaddress_);
  nodename_.Swap(&other->nodename_);
  swap(sizegb_, other->sizegb_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata connect_resp::GetMetadata() const {
  protobuf_datanode_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_datanode_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void disconnect_req::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int disconnect_req::kIpaddressFieldNumber;
const int disconnect_req::kNodenameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

disconnect_req::disconnect_req()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_datanode_2eproto::InitDefaultsdisconnect_req();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:bdfs.disconnect_req)
}
disconnect_req::disconnect_req(const disconnect_req& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ipaddress_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.ipaddress().size() > 0) {
    ipaddress_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ipaddress_);
  }
  nodename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.nodename().size() > 0) {
    nodename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nodename_);
  }
  // @@protoc_insertion_point(copy_constructor:bdfs.disconnect_req)
}

void disconnect_req::SharedCtor() {
  ipaddress_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nodename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

disconnect_req::~disconnect_req() {
  // @@protoc_insertion_point(destructor:bdfs.disconnect_req)
  SharedDtor();
}

void disconnect_req::SharedDtor() {
  ipaddress_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nodename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void disconnect_req::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* disconnect_req::descriptor() {
  ::protobuf_datanode_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_datanode_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const disconnect_req& disconnect_req::default_instance() {
  ::protobuf_datanode_2eproto::InitDefaultsdisconnect_req();
  return *internal_default_instance();
}

disconnect_req* disconnect_req::New(::google::protobuf::Arena* arena) const {
  disconnect_req* n = new disconnect_req;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void disconnect_req::Clear() {
// @@protoc_insertion_point(message_clear_start:bdfs.disconnect_req)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ipaddress_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nodename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool disconnect_req::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:bdfs.disconnect_req)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string ipaddress = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ipaddress()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->ipaddress().data(), static_cast<int>(this->ipaddress().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "bdfs.disconnect_req.ipaddress"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string nodename = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_nodename()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->nodename().data(), static_cast<int>(this->nodename().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "bdfs.disconnect_req.nodename"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:bdfs.disconnect_req)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:bdfs.disconnect_req)
  return false;
#undef DO_
}

void disconnect_req::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:bdfs.disconnect_req)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ipaddress = 1;
  if (this->ipaddress().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ipaddress().data(), static_cast<int>(this->ipaddress().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.disconnect_req.ipaddress");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->ipaddress(), output);
  }

  // string nodename = 2;
  if (this->nodename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nodename().data(), static_cast<int>(this->nodename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.disconnect_req.nodename");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->nodename(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:bdfs.disconnect_req)
}

::google::protobuf::uint8* disconnect_req::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:bdfs.disconnect_req)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ipaddress = 1;
  if (this->ipaddress().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ipaddress().data(), static_cast<int>(this->ipaddress().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.disconnect_req.ipaddress");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->ipaddress(), target);
  }

  // string nodename = 2;
  if (this->nodename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nodename().data(), static_cast<int>(this->nodename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.disconnect_req.nodename");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->nodename(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bdfs.disconnect_req)
  return target;
}

size_t disconnect_req::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bdfs.disconnect_req)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string ipaddress = 1;
  if (this->ipaddress().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->ipaddress());
  }

  // string nodename = 2;
  if (this->nodename().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->nodename());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void disconnect_req::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bdfs.disconnect_req)
  GOOGLE_DCHECK_NE(&from, this);
  const disconnect_req* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const disconnect_req>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bdfs.disconnect_req)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bdfs.disconnect_req)
    MergeFrom(*source);
  }
}

void disconnect_req::MergeFrom(const disconnect_req& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bdfs.disconnect_req)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ipaddress().size() > 0) {

    ipaddress_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ipaddress_);
  }
  if (from.nodename().size() > 0) {

    nodename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nodename_);
  }
}

void disconnect_req::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bdfs.disconnect_req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void disconnect_req::CopyFrom(const disconnect_req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bdfs.disconnect_req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool disconnect_req::IsInitialized() const {
  return true;
}

void disconnect_req::Swap(disconnect_req* other) {
  if (other == this) return;
  InternalSwap(other);
}
void disconnect_req::InternalSwap(disconnect_req* other) {
  using std::swap;
  ipaddress_.Swap(&other->ipaddress_);
  nodename_.Swap(&other->nodename_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata disconnect_req::GetMetadata() const {
  protobuf_datanode_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_datanode_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void disconnect_resp::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int disconnect_resp::kIpaddressFieldNumber;
const int disconnect_resp::kNodenameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

disconnect_resp::disconnect_resp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_datanode_2eproto::InitDefaultsdisconnect_resp();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:bdfs.disconnect_resp)
}
disconnect_resp::disconnect_resp(const disconnect_resp& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ipaddress_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.ipaddress().size() > 0) {
    ipaddress_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ipaddress_);
  }
  nodename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.nodename().size() > 0) {
    nodename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nodename_);
  }
  // @@protoc_insertion_point(copy_constructor:bdfs.disconnect_resp)
}

void disconnect_resp::SharedCtor() {
  ipaddress_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nodename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

disconnect_resp::~disconnect_resp() {
  // @@protoc_insertion_point(destructor:bdfs.disconnect_resp)
  SharedDtor();
}

void disconnect_resp::SharedDtor() {
  ipaddress_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nodename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void disconnect_resp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* disconnect_resp::descriptor() {
  ::protobuf_datanode_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_datanode_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const disconnect_resp& disconnect_resp::default_instance() {
  ::protobuf_datanode_2eproto::InitDefaultsdisconnect_resp();
  return *internal_default_instance();
}

disconnect_resp* disconnect_resp::New(::google::protobuf::Arena* arena) const {
  disconnect_resp* n = new disconnect_resp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void disconnect_resp::Clear() {
// @@protoc_insertion_point(message_clear_start:bdfs.disconnect_resp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ipaddress_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nodename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool disconnect_resp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:bdfs.disconnect_resp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string ipaddress = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ipaddress()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->ipaddress().data(), static_cast<int>(this->ipaddress().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "bdfs.disconnect_resp.ipaddress"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string nodename = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_nodename()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->nodename().data(), static_cast<int>(this->nodename().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "bdfs.disconnect_resp.nodename"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:bdfs.disconnect_resp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:bdfs.disconnect_resp)
  return false;
#undef DO_
}

void disconnect_resp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:bdfs.disconnect_resp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ipaddress = 1;
  if (this->ipaddress().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ipaddress().data(), static_cast<int>(this->ipaddress().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.disconnect_resp.ipaddress");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->ipaddress(), output);
  }

  // string nodename = 2;
  if (this->nodename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nodename().data(), static_cast<int>(this->nodename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.disconnect_resp.nodename");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->nodename(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:bdfs.disconnect_resp)
}

::google::protobuf::uint8* disconnect_resp::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:bdfs.disconnect_resp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ipaddress = 1;
  if (this->ipaddress().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ipaddress().data(), static_cast<int>(this->ipaddress().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.disconnect_resp.ipaddress");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->ipaddress(), target);
  }

  // string nodename = 2;
  if (this->nodename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nodename().data(), static_cast<int>(this->nodename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bdfs.disconnect_resp.nodename");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->nodename(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bdfs.disconnect_resp)
  return target;
}

size_t disconnect_resp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bdfs.disconnect_resp)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string ipaddress = 1;
  if (this->ipaddress().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->ipaddress());
  }

  // string nodename = 2;
  if (this->nodename().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->nodename());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void disconnect_resp::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bdfs.disconnect_resp)
  GOOGLE_DCHECK_NE(&from, this);
  const disconnect_resp* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const disconnect_resp>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bdfs.disconnect_resp)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bdfs.disconnect_resp)
    MergeFrom(*source);
  }
}

void disconnect_resp::MergeFrom(const disconnect_resp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bdfs.disconnect_resp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ipaddress().size() > 0) {

    ipaddress_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ipaddress_);
  }
  if (from.nodename().size() > 0) {

    nodename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nodename_);
  }
}

void disconnect_resp::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bdfs.disconnect_resp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void disconnect_resp::CopyFrom(const disconnect_resp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bdfs.disconnect_resp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool disconnect_resp::IsInitialized() const {
  return true;
}

void disconnect_resp::Swap(disconnect_resp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void disconnect_resp::InternalSwap(disconnect_resp* other) {
  using std::swap;
  ipaddress_.Swap(&other->ipaddress_);
  nodename_.Swap(&other->nodename_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata disconnect_resp::GetMetadata() const {
  protobuf_datanode_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_datanode_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace bdfs

// @@protoc_insertion_point(global_scope)
